In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# 1. Sử dụng numpy để tạo một bộ dữ liệu giả lập
np.random.seed(42)
X = np.random.rand(100, 3)
y = (X[:, 0] + X[:, 1] > 1).astype(int)

In [4]:
X[np.random.choice(X.shape[0], 20), np.random.choice(X.shape[1], 20)] = np.nan

In [5]:
X

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159],
       [0.94888554, 0.96563203, 0.80839735],
       [0.30461377, 0.09767211,        nan],
       [0.44015249, 0.12203823, 0.49517691],
       [0.03438852, 0.9093204 , 0.25877998],
       [       nan, 0.31171108, 0.52006802],
       [0.54671028,        nan, 0.96958463],
       [0.77513282, 0.93949894, 0.89482735],
       [       nan,        nan, 0.0884925 ],
       [0.19598286, 0.04522729, 0.32533033],
       [0.38867729, 0.27134903, 0.82873751],
       [0.35675333, 0.28093451, 0.54269608],
       [0.

In [6]:
y

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [8]:
#  Sử dụng SimpleImputer từ sklearn.impute để điền các giá trị thiếu.
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [9]:
X_test, X_train, y_test, y_train = train_test_split(X, y, test_size=0.3, random_state=42)

In [18]:
imputer = SimpleImputer(strategy="mean")

X_train_imputed = imputer.fit_transform(X_train) #học xong rồi huấn luyện
X_test_imputed = imputer.transform(X_test)

In [15]:
X_train_imputed

array([[0.85300946, 0.29444889, 0.38509773],
       [0.72821635, 0.36778313, 0.63230583],
       [0.54873379, 0.6918952 , 0.65196126],
       [0.32320293, 0.51879062, 0.70301896],
       [0.11986537, 0.33761517, 0.9429097 ],
       [0.18657006, 0.52750249, 0.53934224],
       [0.14092422, 0.80219698, 0.07455064],
       [0.94045858, 0.95392858, 0.91486439],
       [0.60754485, 0.17052412, 0.06505159],
       [0.37454012, 0.95071431, 0.73199394],
       [0.54601524, 0.52750249, 0.0884925 ],
       [0.11959425, 0.71324479, 0.76078505],
       [0.84922341, 0.65761289, 0.5683086 ],
       [0.10789143, 0.03142919, 0.63641041],
       [0.80936116, 0.81011339, 0.86707232],
       [0.83244264, 0.21233911, 0.18182497],
       [0.89204656, 0.63113863, 0.7948113 ],
       [0.50263709, 0.57690388, 0.49251769],
       [0.30461377, 0.09767211, 0.48290233],
       [0.5612772 , 0.77096718, 0.4937956 ],
       [0.8353025 , 0.32078006, 0.18651851],
       [0.87737307, 0.74076862, 0.69701574],
       [0.

In [16]:
X_test_imputed

array([[0.94888554, 0.96563203, 0.80839735],
       [0.2517823 , 0.49724851, 0.30087831],
       [0.55680126, 0.93615477, 0.6960298 ],
       [0.31098232, 0.32518332, 0.72960618],
       [0.79579267, 0.89000534, 0.48290233],
       [0.18340451, 0.30424224, 0.52475643],
       [0.88708642, 0.77987555, 0.64203165],
       [0.34920957, 0.72595568, 0.89711026],
       [0.24929223, 0.41038292, 0.75555114],
       [0.54671028, 0.52750249, 0.96958463],
       [0.50267902, 0.05147875, 0.27864646],
       [0.31435598, 0.50857069, 0.90756647],
       [0.13949386, 0.29214465, 0.36636184],
       [0.03594227, 0.46559802, 0.48290233],
       [0.62329813, 0.33089802, 0.06355835],
       [0.19598286, 0.04522729, 0.32533033],
       [0.3701587 , 0.01545662, 0.92831856],
       [0.72900717, 0.77127035, 0.07404465],
       [0.54601524, 0.55520081, 0.52965058],
       [0.44015249, 0.12203823, 0.49517691],
       [0.00552212, 0.81546143, 0.70685734],
       [0.70807258, 0.02058449, 0.96990985],
       [0.

In [12]:
# 4. Chia dữ liệu thành tập huấn luyện và kiểm tra.
gnb = GaussianNB()

gnb.fit(X_train_imputed, y_train)

y_pred = gnb.predict(X_test_imputed)

# Độ chính xác
acc= accuracy_score(y_test, y_pred)

print(acc)

0.8714285714285714
